[phases.setup]
nixPackages = ["nodejs"]
cmds = [
  "npm install --prefix client",
  "npm install --prefix server"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "cd server && npx prisma generate",
  "npm run build --prefix server"
]

[start]
cmd = "cd server && npx prisma db push --accept-data-loss && node dist/index.js"
