[phases.setup]
nixPackages = ["nodejs"]
cmds = [
  "npm install --include=dev --prefix client",
  "npm install --include=dev --prefix server"
]

[phases.build]
cmds = [
  "npm run build --prefix client",
  "cd server && npx prisma generate",
  "npm run build --prefix server"
]

[start]
cmd = "cd server && npx prisma db push --accept-data-loss && npx tsx src/seed.ts && node dist/index.js"
